### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by gangjun06** [sorarideblog/youtube-study-space#224]
I think this project is a very good with very fresh ideas.
So I want to share this project with Korean people, but the problem is that everything is written in Japanese.
I can't help it if you only want to apply for Japanese, but if not, I would like to add Korean and English to this project.
Even use a different YouTube channel for each language, I think it will be better to select language by env.
I can create I18n module and open PR.

**Comment by sorarideblog** [comment]
@gangjun06 
Thank you,
I have been thinking about multilingual support in the future after I completed what I'm working on.
It's almost only me that works on this project, so more cooperators wanted.

Its' welcome if you and others join to my project.
I will rewrite all issues and source codes in this repository into English as soon as possilbe, so that you can understand the structure.
Please let me know if anything is unclear. 
(I think currently it's hard for aynone but me to regenerate the system environment.)

**Comment by gangjun06** [comment]
Thank you for your comment!
I'll create PR about this issue
